version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  slack: circleci/slack@3.4.2
jobs:
  slack-notifications:
    steps:
      - slack/status
workflows:
  hourly:
    triggers:
      - schedule:
          cron: "0 6-18 * * *"
    jobs:
      - cypress/run
      - slack-notifications